name: Setup node and pnpm
description: Setup node and install dependencies using pnpm
inputs:
  use_lockfile:
    description: 'Whether to use the lockfile vs latest floating dependencies'
    required: false
    default: true
runs:
  using: 'composite'
  steps:
    - uses: volta-cli/action@v4
      env:
        ACTIONS_STEP_DEBUG: truex 
    - name: Get pnpm cache directory path
      id: pnpm-cache-dir-path
      run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/cache@v3
      id: pnpm-cache
      with:
        path: ${{ steps.pnpm-cache-dir-path.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}-v1
        restore-keys: |
          ${{ runner.os }}-pnpm-
    - run: pnpm install ${{ fromJSON('{"false":"--no-lockfile", "true":"--frozen-lockfile"}')[inputs.use_lockfile] }}
      shell: bash
