name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - name: "Show the Plan"
        run: cat .release-plan.json

      - name: "Publish Dry Run"
        run: node ./test-packages/release/src/cli.js publish --dry-run
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}

      - name: "Publish"
        run: node ./test-packages/release/src/cli.js publish
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
